package com.miniamigixv.miniamigixv_app.screens

sealed class Screen(val route: String) {
    data object Login : Screen("login")
    data object Register : Screen("register")
    data object Home : Screen("home")
    data object Weather : Screen("weather")
    data object Music : Screen("music")
    data object Chat : Screen("chat")
    data object Profile : Screen("profile")
    data object Games : Screen("games")
    data object MemoriaNeon : Screen("memoria_neon")
    data object RespiracionConsciente : Screen("respiracion_consciente")
    data object SnakeNeo : Screen("snake_neo")
    data object TicTacToe : Screen("tic_tac_toe")
    data object Study : Screen("study")
    data object Events : Screen("events")
    data object Translator : Screen("translator")
    data object Entertainment : Screen("entertainment")
    data object Blog : Screen("blog")
    data object Support : Screen("support")
    data object AdminCenter : Screen("admin_center")
    data object Tutorial : Screen("tutorial")
    data object Settings : Screen("settings")
    data object Notifications : Screen("notifications")
    data object EditProfile : Screen("edit_profile")
}
